on:
  push:
    branches:
      - master







jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: 'Testing Github action'
        run: pwd
      - name: 'Testing Printing'
        run: echo Mohamed

      - name:  "Login to Docker hub"
      
        run:  docker login --username mohamedadel22 --password dckr_pat_UZ-iKF31FetzacKwxeQcbIWshBw

